#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: 'projects'}
#- {name: '2D',  url: '2d'}
#- {name: '3D',  url: '3d'}
#- {name: 'Other',  url: 'other'}

#- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
#- {name: 'writing',    url: 'about'}
#- {name: 'Contact',  url: 'contact'}

#- {name: 'Tools',  url: 'tools'}
#- {name: 'Shaders',  url: 'shaders'}

#-------------------------------
# Projects Section

projects:
- {name: 'WIP: Towers - A Tiny Game',  url: 'Towers'}
- {name: 'TKI Racer',  url: 'TKIRacer'}
- {name: 'Gibels Quest',   url: 'GibelsQuest'}
- {name: 'WIP Music Visualizer for Outskirts',  url: 'OutskirtsVisualizer'}
- {name: 'Gravity Blade', url: 'GravityBlade'}
- {name: 'Emotion Journal',  url: 'EmotionJournal'}
- {name: 'Danis Inferno',  url: 'DanisInferno'}
- {name: 'Leber Olympiade',  url: 'LeberOlympiade'}
- {name: 'My UK Visa Experience',  url: 'MyUKVisaExperience'}
- {name: 'Clerica',   url: 'Clerica'}
- {name: 'Finlay Founds Magical Return Service',   url: 'FinlayFound'}

- {name: 'Blender Tools',  url: 'BlenderProjects'}
- {name: 'Python Projects',  url: 'Python'}
#- {name: 'Project Four',  url: 'proj-4'}
#- {name: 'Project Four',  url: 'proj-4'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter',   link: 'https://twitter.com/_nan0m_'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'github',    link: 'https://github.com/nan0m'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/fabian-bubla/'}
#- {icon: 'envelope',  link: 'mailto:mailto:l.nguyen.paul@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

#seo:
#  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
#  rel-author: 'https://plus.google.com/u/0/#'
#  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-analytics-ua: 'UA-112060364-3'
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
